# Spring Bootのアプリケーション名
spring.application.name=bulletinboard

#MySQLの接続情報
spring.datasource.url=jdbc:mysql://localhost:3306/bulletinboard?useSSL=false&allowPublicKeyRetrieval=true

#ユーザー名とパスワード
spring.datasource.username=root
spring.datasource.password=password

#ドライバクラス（（Java）とデータベースを“つなぐための専用）
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#「JPA・Hibernate設定」＝Spring Boot がデータベースとやり取りするための“振る舞い”を決める設定の総称。
#
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# EntityとDB構造が合っているか確認するだけに変更
spring.jpa.hibernate.ddl-auto=validate
# 実行されるSQLをコンソールに表示
spring.jpa.show-sql=true
# 出力されるSQLを読みやすく整形
spring.jpa.properties.hibernate.format_sql=true

# =====================================================================
# Flyway
# =====================================================================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

#開発用便利設定

# Spring Webの詳細ログを出力
logging.level.org.springframework.web=debug
# SQLのパラメータ（?の中身）をログに表示
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=trace
# DevToolsによるオートリロード（自動再起動）を有効化
spring.devtools.restart.enabled=true
# Thymeleafのキャッシュを無効化（HTMLの修正を即時反映）
spring.thymeleaf.cache=false
# Thymeleafの詳細ログを出力
logging.level.org.thymeleaf=debug


# ==========================================
# メール送信設定（Mail Settings）
# ==========================================
# SMTPサーバーのホスト名（Gmailの場合）
spring.mail.host=smtp.gmail.com
# SMTPサーバーのポート番号（TLS通信用）
spring.mail.port=587
# 送信元のGoogleアカウントのメールアドレス
spring.mail.username=${MAIL_USERNAME}
# 送信用アプリパスワード（※通常のログインパスワードではありません）
spring.mail.password=${MAIL_PASSWORD}
# SMTP認証を有効化
spring.mail.properties.mail.smtp.auth=true
# STARTTLSによる暗号化通信を有効化
spring.mail.properties.mail.smtp.starttls.enable=true

# メッセージファイルの文字コードをUTF-8に指定
spring.messages.encoding=UTF-8

